POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlyaW5ha29uIiwiaWQiOiI2MjEzYzUzYTUyOTg5ODA1NTU5MGNjMWMiLCJpYXQiOjE2NDYzMjIwNzksImV4cCI6MTY0NjMyNTY3OX0.5vjHpzk29aytfoQIIVrtSG79jU5GUIjmKOgrFy5TfUo

{
  "title": "uusi 123",
  "author": "irina",
  "url": "www",
  "likes": 666
}